### PR TITLE
Fix simulation mode and linux regexp.

### LINKED ISSUE #2: Regex error
Getting what looks like a regex bug. Running on Mac OSX 10.11 with python 3.5

```python
$ gping google.com
Traceback (most recent call last):
  File "/usr/local/bin/gping", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/site-packages/gping/pinger.py", line 251, in run
    for ping in it(url):
  File "/usr/local/lib/python3.5/site-packages/gping/pinger.py", line 225, in _linux
    yield round(float(linux_re.search(line).group(1)))
AttributeError: 'NoneType' object has no attribute 'group'
```

Since there is apparently a failed match the match is None which is why it errors.

### PR DESCRIPTION
**Pull request by p2004a**
It was not possible to start gping in simulation mode.

Your linux regexp didn't match lines containing time without the dot for example here:

    64 bytes from lhr14s23-in-f36.1e100.net (216.58.210.36): icmp_seq=2 ttl=52 time=83.6 ms
    64 bytes from lhr14s23-in-f36.1e100.net (216.58.210.36): icmp_seq=3 ttl=52 time=133 ms

It was unable to match second line (fixes #2 )

I don't know why it was so complicated too. I fixed this issue and simplified the regexp.

### CODE REVIEW

**Comment by jasonsperske** [comment]
Just confirmed that this works on OSX 10.10.5 and Ubuntu 14.10
